#!/bin/sh
QMAILDUID=`id -u smtpd`
NOFILESGID=`id -g smtpd`
LANG=C
exec /usr/local/bin/softlimit -m 75000000 \
  /usr/local/bin/tcpserver -c 10 -v -R -p \
  -u $QMAILDUID -g $NOFILESGID `head -1 config/IP` smtp \
  ./qpsmtpd 2>&1

