#!perl -w

use strict;
use warnings;

sub register_tests {
    my ( $self ) = @_;

    $self->register_test('test_content_log_file');
}

sub test_content_log_file {
    my ( $self ) = @_;
    ok( $self->content_log_file, 'content_log_file() returns something' );
}

