#!perl -w

use strict;
use warnings;

use Qpsmtpd::Constants;
use Test::FakeResolver;

sub register_tests {
    my $self = shift;

    $self->register_test('test_hook_connect');
    $self->register_test('test_ip_whitelisted');
    $self->register_test('test_ip_whitelisted_ipv6');
    $self->register_test('test_reject_type');
}

sub test_ip_whitelisted {
    my $self = shift;

    $self->qp->connection->remote_ip('192.168.99.5');
    ok( $self->ip_whitelisted(), "+");

    $self->qp->connection->remote_ip('192.168.99.6');
    ok( ! $self->ip_whitelisted(), "-");

    $self->qp->connection->remote_ip('192.168.99.5');
    $self->qp->connection->notes('whitelisthost', 'hello honey!');
    ok( $self->ip_whitelisted(), "+");
    $self->qp->connection->notes('whitelisthost', undef);
}

sub test_hook_connect {
    my $self = shift;

    my $conn = $self->qp->connection;
    $conn->relay_client(0);
    $conn->notes($_, undef) for qw(whitelisthost whitelistsender naughty);
    local $self->{_args}{reject} = 1;
    local $self->{_resolver} = Test::FakeResolver->new(
        '1.2.0.192.listed.test' => {A => ['127.0.0.2'], TXT => ['see example']},
        '2.2.0.192.listed.test' => {A => ['127.255.255.254']},
        join('.', reverse(split //, '20010db8' . ('0' x 23) . '1'), 'listed.test')
          => {A => ['127.0.0.2']},
    );

    my @cases = (
        ['192.0.2.1', 'listed.test', [DENY, 'see example'],
         'listed, the TXT record is the reason'],
        ['192.0.2.1', 'listed.test:Blocked %IP%', [DENY, 'Blocked 192.0.2.1'],
         'listed, the configured message is the reason'],
        ['2001:db8::1', 'listed.test', [DENY, 'Blocked by listed.test'],
         'an IPv6 client is looked up'],
        ['192.0.2.2', 'listed.test', [DECLINED],
         'a refused query is not a listing'],
        ['192.0.2.3', 'listed.test', [DECLINED], 'not listed'],
    );
    for (@cases) {
        my ($ip, $zones, $expect, $name) = @$_;
        $conn->remote_ip($ip);
        $self->mock_config(dnsbl_zones => $zones, dnsbl_allow => '');
        is_deeply([$self->hook_connect($self->qp->transaction)], $expect, $name);
    }

    $conn->remote_ip('192.0.2.1');
    $self->mock_config(dnsbl_zones => 'listed.test', dnsbl_allow => '',
                       dnsbl_rejectmsg => 'Ask your ISP.');
    is_deeply([$self->hook_connect($self->qp->transaction)],
              [DENY, 'Ask your ISP. see example'],
              'dnsbl_rejectmsg comes before the reason');
    $self->unmock_config;
}

sub test_ip_whitelisted_ipv6 {
    my $self = shift;

    $self->mock_config(dnsbl_allow => ['2001:DB8:1::/48', '2001:db8:2::5']);
    for (
        ['2001:db8:1:2::5',  1, 'in a CIDR block'],
        ['2001:db8:10::5',   0, 'outside a CIDR block'],
        ['2001:0DB8:2:0::5', 1, 'an address, written another way'],
        ['2001:db8:2::6',    0, 'a different address'],
        ['192.168.99.5',     0, 'IPv4 client, IPv6 entries'],
      )
    {
        my ($ip, $allowed, $desc) = @$_;
        $self->qp->connection->remote_ip($ip);
        is(!!$self->ip_whitelisted(), !!$allowed, "IPv6: $desc");
    }
    $self->unmock_config;
}

sub test_reject_type {
    my $self = shift;

    $self->{_args}{reject_type} = undef;
    cmp_ok( $self->get_reject_type(), '==', DENY, "default");

    $self->{_args}{reject_type} = 'temp';
    cmp_ok( $self->get_reject_type(), '==', DENYSOFT, "defer");

    $self->{_args}{reject_type} = 'disconnect';
    cmp_ok( $self->get_reject_type(), '==', DENY_DISCONNECT, "disconnect");
}
