#!perl -w

sub register_tests {
    my $self = shift;
    $self->register_test("test_auth_flat_file", 3);
}

my @u_list = qw ( good bad none );
my %u_data = (
	      good => [ 'good@example.com', OK, 'good_pass' ],
	      bad => [ 'bad@example.com', DENY, 'not_bad_pass' ],
	      none => [ 'none@example.com', DECLINED, '' ],
	      );

sub test_auth_flat_file {
    my $self = shift;
    my ($tran, $ret, $note, $u, $r, $p, $a );
    $tran = $self->qp->transaction;
    for $u ( @u_list ) {
	( $a,$r,$p ) = @{$u_data{$u}};
	($ret, $note) = $self->auth_flat_file($tran,'CRAMMD5',$a,$p);
	defined $note or $note='authflat: No-Message';
	is ($ret, $r, $note);
	# - for debugging.
	# warn "$note\n";
    }
}
