#!perl -w

=head1 NAME

config/http

=head1 DESCRIPTION

Example config plugin.  Gets configuration data via http requests.

=head1 CONFIG

config/http is configured at plugin loading time via the plugins
config.  Load the plugin with a list of urls like the following (on one line)
 
  config/http http://localhost/~smtpd/config/ http://www.example.com/cgi-bin/qp?config=

Looking to config "me", qpsmtpd will try loading
http://localhost/~smtpd/config/me and if failing that try
http://www.example.com/cgi-bin/qp?config=me

=head1 BUGS

config/http doesn't do any caching.  It should do some simple caching
to be used in production.

=cut

use LWP::Simple qw(get);

my @urls;

sub register {
    my ($self, $qp, @args) = @_;
    @urls = @args;
}

sub hook_config {
    my ($self, $transaction, $config) = @_;
    $self->log(LOGNOTICE, "config/http called with $config");
    for my $url (@urls) {
        $self->log(LOGDEBUG, "config/http loading from $url");
        my @config = split /[\r\n]+/, (get "$url$config" || "");
        chomp @config;
        @config = grep { $_ and $_ !~ m/^\s*#/ and $_ =~ m/\S/ } @config;
        close CF;

        return OK, @config if @config;
    }
    return DECLINED;
}
