#!perl -w

=head1 NAME

dnsbl - handle DNS BlackList lookups

=head1 DESCRIPTION

Plugin that checks the IP address of the incoming connection against
a configurable set of RBL services.

=head1 USAGE

Add the following line to the config/plugins file:

  dnsbl

The following options are also availble:

=head2 reject [ 0 | 1 | naughty ]

  dnsbl reject 0  <- do not reject

  dnsbl reject 1  <- reject

  dnsbl reject naughty  <-  See perldoc plugins/naughty

Also, when I<reject naughty> is set, DNS queries are processed during connect.

=head2 reject_type [ temp | perm | disconnect ]

Default: perm

To immediately drop the connection (since some blacklisted servers attempt
multiple sends per session), set I<reject_type disconnect>. In most cases,
an IP address that is listed should not be given the opportunity to begin a
new transaction, since even the most volatile blacklists will return the same
answer for a short period of time (the minimum DNS cache period).

=head2 loglevel

  dnsbl [loglevel -1]

Adjust the quantity of logging for this plugin. See docs/logging.pod

=head1 CONFIG FILES

This plugin uses the following configuration files. All are optional. Not
specifying dnsbl_zones is like not using the plugin at all.

=head2 dnsbl_zones

One DNS blocklist (RFC 5782) per line, checked in order:

  zen.spamhaus.org
  bl.spamcop.net

A client is listed when the zone has an A record in 127.0.0.0/8 for its
address. IPv6 clients are looked up too; a zone that does not list IPv6
answers that the address is not listed. The rejection gives the zone's TXT
record as the reason. To give your own instead, add it after a colon. %IP%
is replaced with the client's address:

  bl.spamcop.net:Blocked, see https://www.spamcop.net/bl.shtml?%IP%

An answer in 127.255.255.0/24 is an error report: Spamhaus, for one, sends
it to a public resolver or a query over its rate limit. It is logged, and
the client is not rejected. Spamhaus does not answer queries through public
resolvers such as 8.8.8.8, so a server using one needs a local resolver.

=head2 dnsbl_allow

Client addresses that are never looked up, one per line. An IPv4 entry
matches whole octets, so I<172.16.33> matches 172.16.33.0/24. An IPv6 entry
matches the address as written, or the addresses that start with it when it
ends with a colon:

  192.168.1.1
  172.16.33.
  2001:db8:1:

=head2 dnsbl_rejectmsg

Text put before the reason in each rejection, to tell the sender what to do:

  If you think you have been blocked in error, forward this message to your ISP.

=head1 Revisions

See: https://github.com/smtpd/qpsmtpd/commits/master/plugins/dnsbl

=cut

sub register {
    my ($self, $qp) = (shift, shift);

    if (@_ % 2) {
        $self->{_args}{reject_type} = shift;    # backwards compatibility
    }
    else {
        $self->{_args} = {@_};
    }

    # explicitly state legacy reject behavior
    if (!defined $self->{_args}{reject_type}) {
        $self->{_args}{reject_type} = 'perm';
    }
    if (!defined $self->{_args}{reject}) {
        $self->{_args}{reject} = 1;
    }
}

sub hook_connect {
    my ($self, $transaction) = @_;

    return DECLINED if $self->is_immune();
    return DECLINED if $self->ip_whitelisted();

    my @zones = $self->get_dnsbl_zones() or return DECLINED;
    $self->get_resolver(timeout => $self->{_args}{timeout} || 30);

    my $remote_ip = $self->qp->connection->remote_ip;
    my $name = $self->dnsbl_name($remote_ip) or return DECLINED;

    for (@zones) {
        my ($zone, $message) = @$_;
        my $result = $self->dnsbl_lookup("$name.$zone") or next;
        if ($result->{error}) {
            $self->log(LOGERROR, "skip, $result->{error}");
            next;
        }

        $self->adjust_karma(-1);
        my $reason = $message // $result->{reason};
        $reason = "Blocked by $zone" if !length $reason;
        $reason =~ s/%IP%/$remote_ip/g;
        my $advice = join ' ', $self->qp->config('dnsbl_rejectmsg');
        return $self->get_reject(join(' ', grep { length } $advice, $reason),
                                 $zone);
    }

    $self->log(LOGINFO, 'pass');
    return DECLINED;
}

sub get_dnsbl_zones {
    my $self = shift;

    my @zones = map { [split /:/, $_, 2] } $self->qp->config('dnsbl_zones');
    $self->log(LOGDEBUG, "skip, no zones") if !@zones;
    return @zones;
}

sub ip_whitelisted {
    my ($self) = @_;

    my $remote_ip = $self->qp->connection->remote_ip;
    for my $allow ($self->qp->config('dnsbl_allow')) {
        return 1 if $allow eq $remote_ip;

        # an IPv4 entry matches whole octets: 10.1 is 10.1.0.0/16
        my $prefix = $allow =~ /:/ ? $allow : $allow =~ s/\.?$/./r;
        return 1 if $prefix =~ /[.:]$/ && index("$remote_ip.", $prefix) == 0;
    }
    return;
}

sub hook_rcpt {
    my ($self, $transaction, $rcpt, %param) = @_;

    if ($rcpt->user =~ /^(?:postmaster|abuse|mailer-daemon|root)$/i) {
        $self->log(LOGWARN,
                   "skip, don't blacklist special account: " . $rcpt->user);

        # clear the naughty connection note here, if desired.
        $self->is_naughty(0);
    }

    return DECLINED;
}
