#!/usr/bin/perl -w

use Qpsmtpd::Stats;
use Time::HiRes qw(time);

my $START_TIME = time;
our $MAILS_RECEIVED = 0;
our $MAILS_REJECTED = 0;
our $MAILS_TEMPFAIL = 0;

sub register {
    my ($self) = @_;
    
    $self->register_hook('deny', 'increment_deny');
    $self->register_hook('queue', 'increment_mails');
}

sub increment_deny {
    my ($self, $tran, $plugin, $level) = @_;
    
    if ($level == DENY or $level == DENY_DISCONNECT) {
        $MAILS_REJECTED++;
    }
    elsif ($level == DENYSOFT or $level == DENYSOFT_DISCONNECT) {
        $MAILS_TEMPFAIL++;
    }
    
    return DECLINED;
}

sub increment_mails {
    my $self = shift;
    
    $MAILS_RECEIVED++;
    
    return DECLINED;
}

sub uptime {
    return (time() - $START_TIME);
}

sub mails_received {
    return $MAILS_RECEIVED;
}

sub mails_rejected {
    return $MAILS_REJECTED;
}

sub mails_tempfailed {
    return $MAILS_TEMPFAIL;
}

sub mails_per_sec {
    return ($MAILS_RECEIVED / uptime());
}


