#!/usr/bin/perl
#
#  This plugin doesn't actually check anything and will authenticate any
#  user no matter what they type.  It is strictly a proof of concept for
#  the Qpsmtpd::Auth module.  Don't run this in production!!!
#

sub register {
    my ( $self, $qp ) = @_;

    #  $self->register_hook("auth-plain", "authnull");
    #  $self->register_hook("auth-login", "authnull");
    #  $self->register_hook("auth-cram-md5", "authnull");

    $self->register_hook( "auth", "authnull" );
}

sub authnull {
    my ( $self, $transaction, $method, $user, $passClear, $passHash, $ticket ) =
      @_;

    #  $DB::single = 1;
    $self->log( LOGERROR, "authenticating $user using $method" );

    return ( OK, "$user is free to abuse my relay" );
}

