Document: qpsmtpd
Title: Debian qpsmtpd Manual
Author: <insert document author here>
Abstract: This manual describes what qpsmtpd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qpsmtpd/qpsmtpd.sgml.gz

Format: postscript
Files: /usr/share/doc/qpsmtpd/qpsmtpd.ps.gz

Format: text
Files: /usr/share/doc/qpsmtpd/qpsmtpd.text.gz

Format: HTML
Index: /usr/share/doc/qpsmtpd/html/index.html
Files: /usr/share/doc/qpsmtpd/html/*.html
