#!perl -w

=head1 NAME

geoip - provide geographic information about mail senders.

=head1 SYNOPSIS

Use MaxMind's GeoIP2 databases and the GeoIP2 perl module to report
geographic information about incoming connections.

=head1 DESCRIPTION

Save geographic information about the sender in the following connection notes:

  geoip_country      - 2 char country code
  geoip_country_name - english name of country
  geoip_continent    - 2 char continent code
  geoip_city         - english name of city
  geoip_distance     - distance in kilometers
  geoip_asn          - network number

And adds entries like this to your logs:

  (connect) ident::geoip: NA, US, United States,     1319 km
  (connect) ident::geoip: AS, IN, India,            13862 km
  (connect) ident::geoip: fail: no results
  (connect) ident::geoip: NA, CA, Canada,            2464 km
  (connect) ident::geoip: NA, US, United States,     2318 km
  (connect) ident::geoip: AS, PK, Pakistan,         12578 km
  (connect) ident::geoip: AS, TJ, Tajikistan,       11965 km
  (connect) ident::geoip: EU, AT, Austria,           8745 km
  (connect) ident::geoip: AS, IR, Iran, Islamic Republic of, 12180 km
  (connect) ident::geoip: EU, BY, Belarus,           9030 km
  (connect) ident::geoip: AS, CN, China,            11254 km
  (connect) ident::geoip: NA, PA, Panama,            3163 km

Calculating the distance has three prerequisites:

  1. The MaxMind GeoLite2-City database (free or subscription)
  2. The Math::Trig perl module
  3. The IP address of this mail server (see CONFIG)

Other plugins can utilize the geographic notes to alter the
connection, reject, greylist, etc.

=head1 CONFIG

The following options can be appended in this plugins config/plugins entry.

=head2 distance <IP Address>

Enables geodesic distance calculation. Will calculate the distance "as the
crow flies" from the remote mail server. Accepts a single argument, the IP
address to calculate the distance from. This will typically be the public
IP of your mail server.

  ident/geoip [ distance 192.0.1.5 ]

Default: none. (no distance calculations)

=head2 too_far <distance in km>

Assign negative karma to connections further than this many km.

Default: none

=head2 db_dir </path/to/GeoIP>

The path to the GeoIP database directory.

  ident/geoip [ db_dir /etc/GeoIP ]

Default: /usr/local/share/GeoIP

=head2 add_headers <true|false>

Add message headers with GeoIP data

  ident/geoip [ add_headers (true|false) ]

Default: true

=head1 LIMITATIONS

The distance calculations are more concerned with being fast than accurate.
The MaxMind location data is collected from whois and is of limited accuracy.
MaxMind offers more accurate data for a fee.

For distance calculations, the earth is considered a perfect sphere. In
reality, it is not. Accuracy should be within 1%.

This plugin does not update the GeoIP databases. You may want to.

=head1 CHANGES

2026-07 - removed legacy Geo::IP support, GeoIP2 only

2014-06 - Matt Simerson - added GeoIP2 support

2012-06 - Matt Simerson - added GeoIP City support, continent, distance

2012-05 - Matt Simerson - added geoip_country_name note, added tests

=head1 SEE ALSO

MaxMind: http://www.maxmind.com/

Databases: http://geolite.maxmind.com/download/geoip/database

It may become worth adding support for Geo::IPfree, which uses another
data source: http://software77.net/geo-ip/

=head1 ACKNOWLEDGEMENTS

MaxMind - the packager and distributor of the free GeoIP data

Stevan Bajic, the DSPAM author, who suggested SNARE, which describes using
geodesic distance to determine spam probability. The research paper on SNARE
can be found here:
http://smartech.gatech.edu/bitstream/handle/1853/25135/GT-CSE-08-02.pdf

=cut

use strict;
use warnings;

use Qpsmtpd::Constants;

#use GeoIP2;      # eval'ed in register()
#use Math::Trig;  # eval'ed in set_distance

sub register {
    my ($self, $qp, @args) = @_;

    $self->log(LOGERROR, "Bad arguments") if @args % 2;
    $self->{_args} = {@args};
    $self->{_args}{db_dir} ||= '/usr/local/share/GeoIP';

    $self->load_geoip() or return;
    my $enabled = $self->{_args}{add_headers};
    $enabled = 'true' if ! defined $enabled;
    return if $enabled =~ /false/i;
    $self->register_hook( data_post => 'add_headers' );
}

sub load_geoip {
    my $self = shift;

    eval 'use GeoIP2::Database::Reader';
    if ($@) {
        $self->log(LOGERROR, "could not load GeoIP2");
        return;
    }

    eval {
        $self->{_geoip2_city} = GeoIP2::Database::Reader->new(
            file => $self->{_args}{db_dir} . '/GeoLite2-City.mmdb',
        );
    };
    if ($@) {
        $self->log(LOGERROR, "unable to load GeoLite2-City.mmdb");
    }

    eval {
        $self->{_geoip2_country} = GeoIP2::Database::Reader->new(
            file => $self->{_args}{db_dir} . '/GeoLite2-Country.mmdb',
        );
    };
    if ($@) {
        $self->log(LOGERROR, "unable to load GeoLite2-Country.mmdb");
    }

    if ($self->{_geoip2_city} || $self->{_geoip2_country}) {
        $self->register_hook('connect', 'geoip_lookup');
        return 1;
    }

    return;
}

sub add_headers {
    my ( $self, $txn ) = @_;
    for my $h (qw( Country Continent City ASN )) {
        my $note = lc "geoip_$h";
        next if ! $self->connection->notes($note);
        $txn->header->delete("X-GeoIP-$h");
        $txn->header->add( "X-GeoIP-$h", $self->connection->notes($note), 0 );
    }
    return DECLINED;
}

sub geoip_lookup {
    my $self = shift;

    my $ip = $self->qp->connection->remote_ip;
    return DECLINED if $self->is_localhost($ip);

    if ($self->{_geoip2_city}) {
        my $city_rec = eval { $self->{_geoip2_city}->city(ip => $ip) };
        if ($city_rec) {
            $self->qp->connection->notes('geoip_country', $city_rec->country->iso_code());
            $self->qp->connection->notes('geoip_country_name', $city_rec->country->name());
            $self->qp->connection->notes('geoip_continent', $city_rec->continent->code());
            $self->qp->connection->notes('geoip_city', $city_rec->city->name());
            $self->qp->connection->notes('geoip_asn', $city_rec->traits->autonomous_system_number());
            $self->set_distance($city_rec);
            return DECLINED;
        }
    }

    if ($self->{_geoip2_country}) {
        my $country_rec = eval { $self->{_geoip2_country}->country(ip => $ip) };
        if ($country_rec) {
            $self->qp->connection->notes('geoip_country', $country_rec->country->iso_code());
            $self->qp->connection->notes('geoip_country_name', $country_rec->country->name());
            $self->qp->connection->notes('geoip_continent', $country_rec->continent->code());
        };
    }

    return DECLINED;
}

# Notice the 90 - latitude: phi zero is at the North Pole.
sub NESW { deg2rad($_[0]), deg2rad(90 - $_[1]) }

sub set_distance {
    my ($self, $sender_rec) = @_;

    my ($self_lat,   $self_lon)   = $self->get_my_lat_lon()             or return;
    my ($sender_lat, $sender_lon) = $self->get_sender_lat_lon($sender_rec) or return;

    eval 'use Math::Trig qw(great_circle_distance deg2rad)';
    if ($@) {
        $self->log(LOGERROR,
                   "can't calculate distance, Math::Trig not installed");
        return;
    }

    my @me     = NESW($self_lon,   $self_lat);
    my @sender = NESW($sender_lon, $sender_lat);
    my $km = great_circle_distance(@me, @sender, 6378);
    $km = sprintf("%.0f", $km);

    $self->qp->connection->notes('geoip_distance', $km);

    if ($self->{_args}{too_far} && $km > $self->{_args}{too_far}) {
        $self->adjust_karma(-1);
    }

    return $km;
}

sub get_my_lat_lon {
    my $self = shift;
    return if !$self->{_geoip2_city};

    if (defined $self->{_latitude} && defined $self->{_longitude}) {
        return $self->{_latitude}, $self->{_longitude};    # cached
    }

    my $ip = $self->{_args}{distance} or return;
    my $record = eval { $self->{_geoip2_city}->city(ip => $ip) } or do {
        $self->log(LOGERROR, "no record for my GeoIP location");
        return;
    };

    $self->{_latitude}  = $record->location->latitude();
    $self->{_longitude} = $record->location->longitude();

    if (!defined $self->{_latitude} || !defined $self->{_longitude}) {
        $self->log(LOGNOTICE, "could not get my lat/lon");
    }
    return $self->{_latitude}, $self->{_longitude};
}

sub get_sender_lat_lon {
    my ($self, $sender_rec) = @_;

    my $lat = $sender_rec->location->latitude();
    my $lon = $sender_rec->location->longitude();
    if (!defined $lat || !defined $lon) {
        $self->log(LOGNOTICE, "could not get sender lat/lon");
        return;
    }
    return $lat, $lon;
}
